# Generated by Django 3.1.6 on 2021-06-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=120, unique=True)),
                ('author', models.CharField(max_length=120)),
                ('price', models.FloatField()),
                ('pages', models.IntegerField()),
            ],
        ),
    ]
